steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-web-app', '.']
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-web-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'my-web-app'  # Service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-web-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'  # Change this to your desired region
      - '--allow-unauthenticated'  # Change if you want authentication
